FROM jboss/wildfly
ADD justBillMeWeb.war /opt/jboss/wildfly/standalone/deployments/

#docker-dir/justBillMeWeb archive.war
#C:\Users\bybox\IdeaProjects\com.justbill.me\docker-dir\justBillMeWeb archive.war